services:
  - type: web
    name: django-app
    runtime: docker
    repo: https://github.com/yourusername/yourrepo  # Update with your repo URL
    branch: main  # Change to the branch you want to deploy from
    plan: free  # Change to "starter", "standard", etc., if needed
    envVars:
      - key: PORT
        value: 8000
    dockerContext: .  # The directory where your Dockerfile is located
    dockerfilePath: Dockerfile  # Path to your Dockerfile
    startCommand: "sh /app/build.sh"
    autoDeploy: true
